export const codes = {
  GRAVITY: "Happy Birthday! You're just as mysterious as this code!",
  HAPPYBIRTHDAY: "Another year, another mystery solved. Or is it?",
  SECRET32: "The answer to life, the universe, and... your birthday!",
  DECODEX: "Descifrador de códigos, dales buen uso.",
  YOYO: "Una criatura muy hermosa en muchas dimensiones multiversales, bill tiene una!.",
  MYSTERY: "Wow lo lograste, es solo el comienzo",
  BILL: "Asi que quieres saber mas sobre mi...",
  BILLCIPHER: "Soy una idea perfectamente geometrica.",
  DORITO: "No debiste decirme eso.",
  MUERTE: "LA PRIMA GÓTICA DE LA VIDA.",
  ANSWER: "QUESTION",
  ASSHOLE: 'NOT S&P approved, wash your mouth out with soap!',
  CUM: "NOT S&P approved, wash your mouth out with soap!",
  BITCH: "NOT S&P approved, wash your mouth out with soap!",
  AXOLOTL: "HACES MUCHAS PREGUNTAS...",
  BABY: "FELICIDADES, ADIVINA QUÉ ESTÁ CRECIENDO DENTRO DE TI AHORA MISMO. ¡NOS VEMOS EN 9 MESES, PAPÁ!",
  BABYBILL: "FELICIDADES, ADIVINA QUÉ ESTÁ CRECIENDO DENTRO DE TI AHORA MISMO. ¡NOS VEMOS EN 9 MESES, PAPÁ!",
  HL1: "Stahppppppppppppppppp!",
  HL2: "Lamar!!, donde estas!?",
  HL3: "Bill tambien perdio la esperanza de algún día ver ese 3...",
  CRYPTOGRAMCODEX: "Bien!, recibe las fuentes de cryptogramas codificados, dales un buen uso.",
  BLENDIN: "Agente de tiempo perdido y presunto incompetente",
  BLENDINBLANDIN: "Agente de tiempo perdido y presunto incompetente",
  BLENDINBLENJAMINBLANDIN: "Agente de tiempo perdido y presunto incompetente",
  LIFE: "LIFE: 72% COMPLETE, NOW LOADING: DEATH",
  BREAKUP: "O'Sadleys",
  BURNEDINSIDE: "🌲",
  BURNSIDE: "BURNEDINSIDE",
  BUTTERNUBBINS: "you've earned a treat! enter 'DISPENSEMYTREAT' to download",
  DISPENSEMYTREAT: "wallpapers, 🦓✨",
  BYEGOLD: "BYE!",
  CARD: "DREAM DEMON",
  CHIP: "No debiste decirme eso.",
  CIA: "TU CAMARÁ WEB ESTA ENCENDIDA, ESTAMOS MIRANDO.",
  CIPHERTOLOGY: "MANTÉN LA MENTE ABIERTA",
  CLONE: "¡Ahora es tu problema! ¡Solo mantenlo alejado de líquidos!",
  CONSPIRACY: "conspiracion?!",
  CRAZ: "Mabel te dice que eres el mejor.",
  CREEPYPASTA: "△: Lo tenia que hacer amigo, jajajaja",
  CRYPTO: "PRIVILEGIOS DE VIDA REVOCADOS, AHORA LIBERAN GAS VENENOSO.",
  CUNT: "NOT S&P approved, wash your mouth out with soap!",
  CURSEWITTEBANE: "OUIJA",
  DEERTEETH: "Para ti niño 😉",
  DICK: "NOT S&P approved, wash your mouth out with soap!",
  DIONARAP: "..",
  DIPPYFRESH: "Burger King Kid's Club",
  DISCOGIRL: "DISCOGIRL",
  DISNEY: "RAT:GIF, censurado por su protección",
  DISNEYLAND: "RAT:GIF, censurado por su protección",
  DOESGODEXIST: "no existe",
  RICK: "RICKROLLEADO EN 2024",
  DOGE: "PRIVILEGIOS DE VIDA REVOCADOS, AHORA LIBERAN GAS VENENOSO.",
  DUCKTECTIVE: `DuckTective STARS in "love, quacktually" coming to: "OI, its the cockney channel innit?" this fall`,
  EASTEREGG: "EASTER EGGS? SUENA A CONSPIRACIÓN",
  ELON: "PRIVILEGIOS DE VIDA REVOCADOS, AHORA LIBERAN GAS VENENOSO.",
  EPCOT: "RAT:GIF, censurado por su protección",
  EMMALINEBUTTERNUBBINS: "you've earned a treat! enter 'DISPENSEMYTREAT' to download",
  EUCLID: "FORMA DE VIDA NO ENCONTRADA...",
  EUCLYDIA: "DIMENSIÓN NO ENCONTRADA",
  FACEOFGOD: "LA CARA DE DIOS?",
  MARCELO: "lo conociste!",
  DOTA: "Vi sitter i ventrilo och spelar DotA",
  WELLMEETAGAIN: "BILL: nooo!, como apago esto!!?",
  CODES: "Desbloqueaste todos los códigos!, recuerda que tambien puedes descubrirlos!",

  // CURSED: "TODO: hacer zoom" =>  destructionisaformofcreation https://codepen.io/angrygabo/pen/KKVKedJ
  // Puedes agregar más códigos aquí.
};