export const codes = {
  GRAVITY: "Happy Birthday! You're just as mysterious as this code!",
  HAPPYBIRTHDAY: "Another year, another mystery solved. Or is it?",
  SECRET32: "The answer to life, the universe, and... your birthday!",
  "+D1": "#t3441f@fla0",
  YOYO: "Una criatura muy hermosa en muchas dimensiones multiversales, bill tiene una!.",
  MYSTERY: "Wow lo lograste, es solo el comienzo",
  BILL: "Asi que quieres saber mas sobre mi...",
  BILLCIPHER: "Soy una idea perfectamente geometrica.",
  DORITO: "No debiste decirme eso.",
  MUERTE: "¿Que es eso?",
  ANSWER: "QUESTION",
  ASSHOLE: 'NOT S&P approved, wash your mouth out with soap!',
  CUM: "NOT S&P approved, wash your mouth out with soap!",
  BITCH: "NOT S&P approved, wash your mouth out with soap!",
  AXOLOTL: "HACES MUCHAS PREGUNTAS...",
  BABY: "FELICIDADES, ADIVINA QUÉ ESTÁ CRECIENDO DENTRO DE TI AHORA MISMO. ¡NOS VEMOS EN 9 MESES, PAPÁ!",
  BABYBILL: "FELICIDADES, ADIVINA QUÉ ESTÁ CRECIENDO DENTRO DE TI AHORA MISMO. ¡NOS VEMOS EN 9 MESES, PAPÁ!",
  HL1: "Stahppppppppppppppppp!",
  HL2: "Lamar!!, donde estas!?",
  HL3: "Bill tambien perdio la esperanza de algún día ver ese 3...",
  CRYPTOGRAMCODEX: "Bien!, recibe los cryptogramas codificados, dales un buen uso.",
  BLENDIN: "Agente de tiempo perdido y presunto incompetente",
  BLENDINBLANDIN: "Agente de tiempo perdido y presunto incompetente",
  BLENDINBLENJAMINBLANDIN: "Agente de tiempo perdido y presunto incompetente",
  LIFE: "LIFE: 72% COMPLETE, NOW LOADING: DEATH",
  BREAKUP: "O'Sadleys"
  // Puedes agregar más códigos aquí.
};